### ISSUE TITLE
GenerateBlobs - format error

### ISSUE THREAD

**Issue by kuiperzone** [demot/RandomOrgJson-RPC#3]
In the following method in RandomOrgApiClient.cs:
        public Response GenerateBlobs(int n, int size, int id, bool signed, string format = "base64") {

fails due to this line:
            if(format != "base64" || format != "hex")

Needs to be:
            if(format != "base64" && format != "hex")

Has this code been unit tested at all?

**Comment by demot** [comment]
That line is kind of nonsense, you are right.
The code itself is not unit tested because of a lack of experience with unit tests in that time. I will commit a change to that format nonsense condition soon, but the overall issue of untested parts of the code still remains, due to a lack of time right now.

**Comment by kuiperzone** [comment]
Thanks for replies and thanks for the library. Am making use of it and may drop you a further message or two.

**Comment by demot** [comment]
Nice to here about that! and please keep me updated!

**Comment by demot** [comment]
I pushed a fix. The issue should be solved.
A small unit test is also included in a seperate project. When I have more time, I will include more test methods, but for the meantime the library should be usable again.
